-- colors/wallpaper.lua — generated by cli.py, do not edit palette directly
-- Regenerate: python3 cli.py theme --targets nvim

local M = {}

-- ─── Palette ────────────────────────────────────────────────────────────────
M.colors = {
  crust = '#0f0f1f',
  mantle = '#191926',
  base = '#14141c',
  surface0 = '#22222f',
  surface1 = '#2d2d3d',
  surface2 = '#3a3a4d',
  overlay0 = '#5a5c78',
  overlay1 = '#73758f',
  overlay2 = '#8c8ea6',
  subtext0 = '#9698b3',
  subtext1 = '#aaacc4',
  text = '#d4d6f0',
  lavender = '#9d8cff',
  blue = '#6e9bff',
  sapphire = '#5ce8d8',
  sky = '#5ce0f5',
  teal = '#4dd8b0',
  green = '#7dff9e',
  yellow = '#ffe06e',
  peach = '#ffb15c',
  maroon = '#e8546a',
  red = '#ff6e7a',
  mauve = '#c478ff',
  pink = '#ff8fc9',
  flamingo = '#ff9f8a',
  rosewater = '#ffc4a3',
}

-- ─── Semantic aliases ────────────────────────────────────────────────────────
local p = M.colors
local c = {
  bg = p.base,
  bg_dark = p.crust,
  bg_sel = p.surface0,
  bg_subtle = p.surface1,
  fg_dim = p.surface2,
  fg = p.text,
  fg_bright = p.rosewater,
  fg_alt = p.lavender,
  red = p.red,
  peach = p.peach,
  yellow = p.yellow,
  green = p.green,
  teal = p.teal,
  blue = p.blue,
  mauve = p.mauve,
  lavender = p.lavender,
  flamingo = p.flamingo,
  sky = p.sky,
  sapphire = p.sapphire,
  maroon = p.maroon,
  pink = p.pink,
  none = 'NONE',
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ─── Transparency ────────────────────────────────────────────────────────────
local state_path = vim.fn.stdpath('data') .. '/wallpaper_state'

local function state_read()
  local f = io.open(state_path, 'r')
  if not f then
    return false
  end
  local v = f:read('*l')
  f:close()
  return v == 'transparent'
end

local function state_write(enable)
  local f = io.open(state_path, 'w')
  if not f then
    return
  end
  f:write(enable and 'transparent' or 'opaque')
  f:close()
end

M.transparent = state_read()

local transparent_bgs = {
  Normal = { fg = c.fg, bg = c.bg_dark },
  NormalNC = { fg = c.fg_alt, bg = c.bg_dark },
  NormalFloat = { fg = c.fg, bg = c.bg_dark },
  SignColumn = { fg = c.bg_sel, bg = c.bg },
  FoldColumn = { fg = c.fg_dim, bg = c.bg },
  StatusLine = { fg = c.fg_alt, bg = c.bg_dark },
  StatusLineNC = { fg = c.fg_dim, bg = c.bg },
  WinBar = { fg = c.fg_alt, bg = c.bg },
  WinBarNC = { fg = c.fg_dim, bg = c.bg },
  WinSeparator = { fg = c.bg_sel, bg = c.bg },
  TabLine = { fg = c.fg_dim, bg = c.bg_dark },
  TabLineFill = { bg = c.bg },
  TabLineSel = { fg = c.mauve, bg = c.bg, bold = true },
  Pmenu = { fg = c.fg_alt, bg = c.bg_dark },
  PmenuSbar = { bg = c.bg_sel },
  FloatBorder = { fg = c.bg_sel, bg = c.bg_dark },
  FloatTitle = { fg = c.mauve, bg = c.bg_dark, bold = true },
  FidgetTitle = { fg = p.overlay1, bg = p.mantle },
  FidgetTask = { fg = p.overlay0, bg = p.mantle },
  CursorLine = { bg = c.bg_dark },
  CursorColumn = { bg = c.bg_dark },
  DiagnosticVirtualTextError = { fg = c.red, bg = c.bg, italic = true },
  DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.bg, italic = true },
  DiagnosticVirtualTextInfo = { fg = c.teal, bg = c.bg, italic = true },
  DiagnosticVirtualTextHint = { fg = c.sky, bg = c.bg, italic = true },
  LspInlayHint = {
    fg = c.fg_dim,
    bg = c.bg_dark,
    italic = true,
    nocombine = true,
  },
  TelescopeNormal = { fg = c.fg, bg = c.bg_dark },
  TelescopeBorder = { fg = c.bg_sel, bg = c.bg_dark },
  TelescopePromptNormal = { bg = c.bg },
  TelescopePromptBorder = { fg = c.bg_sel, bg = c.bg },
  TelescopePromptTitle = { fg = c.yellow, bg = c.bg_dark },
  TelescopeResultsNormal = { bg = c.bg_dark },
  TelescopeResultsBorder = { fg = c.bg_sel, bg = c.bg_dark },
  TelescopeResultsTitle = { fg = c.bg_dark, bg = c.bg_dark },
  TelescopePreviewNormal = { bg = c.bg },
  TelescopePreviewBorder = { fg = c.bg_sel, bg = c.bg },
  TroubleNormal = { fg = c.fg, bg = c.bg_dark },
  TroubleNormalNC = { fg = c.fg_alt, bg = c.bg_dark },
  WhichKeyNormal = { bg = c.bg_dark },
  MiniFilesNormal = { fg = c.fg, bg = c.bg_dark },
  MiniFilesBorder = { fg = c.bg_sel, bg = c.bg_dark },
  MiniFilesBorderModified = { fg = c.yellow, bg = c.bg_dark },
  MasonNormal = { bg = c.bg_dark },
  ToggleTermNormal = { bg = c.bg },
}

local lualine_bg_cache = {}

local function apply_transparent(enable)
  for group, orig in pairs(transparent_bgs) do
    if enable then
      local no_bg = {}
      for k, v in pairs(orig) do
        if k ~= 'bg' and k ~= 'ctermbg' then
          no_bg[k] = v
        end
      end
      vim.api.nvim_set_hl(0, group, no_bg)
    else
      vim.api.nvim_set_hl(0, group, orig)
    end
  end

  local lualine_modes = { 'normal', 'insert', 'visual', 'replace', 'command', 'terminal', 'inactive' }
  local lualine_sections = { 'a', 'b', 'c', 'x', 'y', 'z' }
  if enable then
    lualine_bg_cache = {}
    for _, mode in ipairs(lualine_modes) do
      for _, section in ipairs(lualine_sections) do
        local name = 'lualine_' .. section .. '_' .. mode
        local hl = vim.api.nvim_get_hl(0, { name = name })
        if hl and hl.bg then
          lualine_bg_cache[name] = vim.deepcopy(hl)
          local no_bg = {}
          for k, v in pairs(hl) do
            if k ~= 'bg' then
              no_bg[k] = v
            end
          end
          vim.api.nvim_set_hl(0, name, no_bg)
        end
      end
    end
  else
    for name, hl in pairs(lualine_bg_cache) do
      vim.api.nvim_set_hl(0, name, hl)
    end
    lualine_bg_cache = {}
  end
end

M.apply_transparent = apply_transparent

function M.set_transparent(enable)
  M.transparent = enable
  state_write(enable)
  apply_transparent(enable)
  vim.notify(
    'wallpaper: transparency ' .. (enable and 'on' or 'off'),
    vim.log.levels.INFO,
    { title = 'wallpaper' }
  )
end

function M.toggle_transparent()
  M.set_transparent(not M.transparent)
end

function M.load()
  vim.cmd('highlight clear')
  if vim.fn.exists('syntax_on') then
    vim.cmd('syntax reset')
  end
  vim.o.termguicolors = true
  vim.g.colors_name = 'wallpaper'

  -- ─── Editor chrome ────────────────────────────────────────────────────────
  hi('Normal', { fg = c.fg, bg = c.bg_dark })
  hi('NormalFloat', { fg = c.fg, bg = c.bg_dark })
  hi('NormalNC', { fg = c.fg_alt, bg = c.bg_dark })
  hi('FloatBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('FloatTitle', { fg = c.mauve, bg = c.bg_dark, bold = true })

  hi('@neovim.logo.N', { fg = c.mauve })
  hi('@neovim.logo', { fg = c.mauve })
  hi('@neovim.version', { fg = c.green })

  hi('Cursor', { fg = c.bg, bg = c.mauve })
  hi('CursorLine', { bg = c.bg_dark })
  hi('CursorLineNr', { fg = c.mauve, bold = true })
  hi('CursorColumn', { bg = c.bg_dark })

  hi('LineNr', { fg = c.bg_sel })
  hi('SignColumn', { fg = c.bg_sel, bg = c.bg })
  hi('ColorColumn', { bg = p.surface1 })
  hi('FoldColumn', { fg = c.fg_dim, bg = c.bg })
  hi('Folded', { fg = c.overlay0, bg = c.none })

  hi('StatusLine', { fg = c.fg_alt, bg = c.bg_dark })
  hi('StatusLineNC', { fg = c.fg_dim, bg = c.bg })
  hi('WinBar', { fg = c.fg_alt, bg = c.bg })
  hi('WinBarNC', { fg = c.fg_dim, bg = c.bg })
  hi('WinSeparator', { fg = c.bg_sel, bg = c.bg })

  hi('TabLine', { fg = c.fg_dim, bg = c.bg_dark })
  hi('TabLineFill', { bg = c.bg })
  hi('TabLineSel', { fg = c.mauve, bg = c.bg, bold = true })

  hi('Pmenu', { fg = c.fg_alt, bg = c.bg_dark })
  hi('PmenuSel', { fg = c.bg, bg = c.mauve, bold = true })
  hi('PmenuSbar', { bg = c.bg_sel })
  hi('PmenuThumb', { bg = c.fg_dim })
  hi('PmenuBorder', { fg = c.bg_sel, bg = c.bg_dark })

  hi('Search', { fg = c.bg, bg = c.yellow })
  hi('IncSearch', { fg = c.bg, bg = c.peach, bold = true })
  hi('CurSearch', { fg = c.bg, bg = c.peach, bold = true })
  hi('Substitute', { fg = c.bg, bg = c.red })

  hi('Visual', { bg = c.bg_sel })
  hi('VisualNOS', { bg = c.bg_subtle })
  hi('MatchParen', { bold = true, underline = true })

  hi('NonText', { fg = c.bg_sel })
  hi('SpecialKey', { fg = c.fg_dim })
  hi('Whitespace', { fg = c.bg_subtle })
  hi('EndOfBuffer', { fg = c.bg_subtle })
  hi('Conceal', { fg = c.fg_dim })

  hi('Directory', { fg = c.blue })
  hi('Title', { fg = c.mauve, bold = true })
  hi('Question', { fg = c.teal })
  hi('MoreMsg', { fg = c.teal })
  hi('ModeMsg', { fg = c.fg_alt })
  hi('ErrorMsg', { fg = c.red })
  hi('WarningMsg', { fg = c.yellow })

  hi('SpellBad', { sp = c.red, undercurl = true })
  hi('SpellCap', { sp = c.yellow, undercurl = true })
  hi('SpellRare', { sp = c.teal, undercurl = true })
  hi('SpellLocal', { sp = c.blue, undercurl = true })

  hi('QuickFixLine', { fg = c.mauve, bg = c.bg_sel })

  -- notify
  hi('NotifyERRORBorder', { fg = c.red })
  hi('NotifyWARNBorder', { fg = c.yellow })
  hi('NotifyINFOBorder', { fg = c.teal })
  hi('NotifyDEBUGBorder', { fg = c.fg_dim })
  hi('NotifyTRACEBorder', { fg = c.mauve })
  hi('NotifyERRORIcon', { fg = c.red })
  hi('NotifyWARNIcon', { fg = c.yellow })
  hi('NotifyINFOIcon', { fg = c.teal })
  hi('NotifyDEBUGIcon', { fg = c.fg_dim })
  hi('NotifyTRACEIcon', { fg = c.mauve })
  hi('NotifyERRORTitle', { fg = c.red, bold = true })
  hi('NotifyWARNTitle', { fg = c.yellow, bold = true })
  hi('NotifyINFOTitle', { fg = c.teal, bold = true })
  hi('NotifyDEBUGTitle', { fg = c.fg_dim, bold = true })
  hi('NotifyTRACETitle', { fg = c.mauve, bold = true })
  hi('NotifyERRORBody', { fg = c.fg, bg = c.bg_dark })
  hi('NotifyWARNBody', { fg = c.fg, bg = c.bg_dark })
  hi('NotifyINFOBody', { fg = c.fg, bg = c.bg_dark })
  hi('NotifyDEBUGBody', { fg = c.fg, bg = c.bg_dark })
  hi('NotifyTRACEBody', { fg = c.fg, bg = c.bg_dark })

  -- blink
  hi('BlinkCmpMenu', { fg = c.fg_alt, bg = c.bg_dark })
  hi('BlinkCmpMenuBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BlinkCmpMenuSelection', { fg = c.fg, bg = c.bg_sel })
  hi('BlinkCmpScrollBarThumb', { bg = c.fg_dim })
  hi('BlinkCmpScrollBarGutter', { bg = c.bg_dark })
  hi('BlinkCmpLabel', { fg = c.fg_alt })
  hi('BlinkCmpLabelMatch', { fg = c.yellow, bold = true })
  hi('BlinkCmpLabelDeprecated', { fg = c.fg_dim, strikethrough = true })
  hi('BlinkCmpKind', { fg = c.mauve })
  hi('BlinkCmpDoc', { fg = c.fg, bg = c.bg_dark })
  hi('BlinkCmpDocBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BlinkCmpDocSeparator', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BlinkCmpSignatureHelp', { fg = c.fg, bg = c.bg_dark })
  hi('BlinkCmpSignatureHelpBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BlinkCmpGhostText', { fg = c.fg_dim, italic = true })

  -- grug
  hi('GrugFarResultsMatch', { fg = c.bg, bg = c.yellow, bold = true })
  hi('GrugFarResultsMatchAdded', { fg = c.bg, bg = c.green })
  hi('GrugFarResultsMatchRemoved', { fg = c.bg, bg = c.red })
  hi('GrugFarResultsPath', { fg = c.blue, bold = true })
  hi('GrugFarResultsLineNo', { fg = c.fg_dim })
  hi('GrugFarResultsStats', { fg = c.mauve, italic = true })
  hi('GrugFarInputLabel', { fg = c.mauve, bold = true })
  hi('GrugFarInputPlaceholder', { fg = c.fg_dim, italic = true })

  -- ─── nvim-ufo ─────────────────────────────────────────────────────────────
  hi('UfoFoldIcon', { fg = p.overlay1 })
  hi('UfoFoldCount', { fg = p.overlay0 })
  hi('UfoFoldedEllipsis', { fg = p.overlay0 })
  hi('UfoPeekedLine', { bg = p.surface0 })

  -- ─── Diff ─────────────────────────────────────────────────────────────────
  hi('DiffAdd', { fg = c.green, bg = c.bg })
  hi('DiffChange', { fg = c.yellow, bg = c.bg })
  hi('DiffDelete', { fg = c.red, bg = c.bg })
  hi('DiffText', { fg = c.blue, bg = c.bg_sel })
  hi('Added', { fg = c.green })
  hi('Changed', { fg = c.yellow })
  hi('Removed', { fg = c.red })

  -- ─── Syntax ───────────────────────────────────────────────────────────────
  hi('Comment', { fg = c.fg_dim, italic = true })
  hi('SpecialComment', { fg = c.bg_subtle, italic = true })
  hi('Constant', { fg = c.peach })
  hi('String', { fg = c.teal })
  hi('Character', { fg = c.teal })
  hi('Number', { fg = c.peach })
  hi('Boolean', { fg = c.peach })
  hi('Float', { fg = c.peach })
  hi('Identifier', { fg = c.fg })
  hi('Function', { fg = c.blue })
  hi('Statement', { fg = c.mauve })
  hi('Conditional', { fg = c.mauve })
  hi('Repeat', { fg = c.mauve })
  hi('Label', { fg = c.mauve })
  hi('Operator', { fg = c.sky })
  hi('Keyword', { fg = c.mauve })
  hi('Exception', { fg = c.red })
  hi('PreProc', { fg = c.pink })
  hi('Include', { fg = c.mauve })
  hi('Define', { fg = c.mauve })
  hi('Macro', { fg = c.pink })
  hi('PreCondit', { fg = c.mauve })
  hi('Type', { fg = c.yellow })
  hi('StorageClass', { fg = c.mauve })
  hi('Structure', { fg = c.yellow })
  hi('Typedef', { fg = c.yellow })
  hi('javaTypedef', { fg = c.red })
  hi('Special', { fg = c.peach })
  hi('SpecialChar', { fg = c.peach })
  hi('Tag', { fg = c.mauve })
  hi('Delimiter', { fg = c.fg_dim })
  hi('Debug', { fg = c.red })
  hi('Underlined', { underline = true })
  hi('Bold', { bold = true })
  hi('Italic', { italic = true })
  hi('Ignore', { fg = c.bg_sel })
  hi('Error', { fg = c.red })
  hi('Todo', { fg = c.bg, bg = c.yellow, bold = true })
  hi('TodoSignTODO', { fg = c.blue })
  hi('TodoSignFIX', { fg = c.red })
  hi('TodoSignHACK', { fg = c.yellow })
  hi('TodoSignWARN', { fg = c.yellow })
  hi('TodoSignPERF', { fg = c.mauve })
  hi('TodoSignNOTE', { fg = c.teal })
  hi('TodoSignTEST', { fg = c.sky })

  -- ─── Treesitter ───────────────────────────────────────────────────────────
  hi('@variable', { fg = c.fg })
  hi('@variable.builtin', { fg = c.red })
  hi('@variable.parameter', { fg = c.maroon })
  hi('@variable.member', { fg = c.fg })
  hi('@constant', { fg = c.peach })
  hi('@constant.builtin', { fg = c.peach })
  hi('@constant.macro', { fg = c.pink })
  hi('@string', { fg = c.teal })
  hi('@string.escape', { fg = c.peach })
  hi('@string.special', { fg = c.peach })
  hi('@string.regexp', { fg = c.peach })
  hi('@character', { fg = c.teal })
  hi('@number', { fg = c.peach })
  hi('@number.float', { fg = c.peach })
  hi('@boolean', { fg = c.peach })
  hi('@function', { fg = c.blue })
  hi('@function.builtin', { fg = c.sky })
  hi('@function.call', { fg = c.blue })
  hi('@function.macro', { fg = c.pink })
  hi('@function.method', { fg = c.blue })
  hi('@function.method.call', { fg = c.blue })
  hi('@constructor', { fg = c.yellow })
  hi('@operator', { fg = c.sky })
  hi('@keyword', { fg = c.mauve })
  hi('@keyword.function', { fg = c.mauve })
  hi('@keyword.operator', { fg = c.sky })
  hi('@keyword.import', { fg = c.mauve })
  hi('@keyword.return', { fg = c.pink })
  hi('@keyword.exception', { fg = c.red })
  hi('@keyword.conditional', { fg = c.mauve })
  hi('@keyword.repeat', { fg = c.mauve })
  hi('@keyword.modifier', { fg = c.mauve })
  hi('@type', { fg = c.yellow })
  hi('@type.builtin', { fg = c.yellow })
  hi('@type.definition', { fg = c.yellow })
  hi('@type.qualifier', { fg = c.mauve })
  hi('@attribute', { fg = c.peach })
  hi('@property', { fg = c.fg_alt })
  hi('@comment', { fg = c.fg_dim, italic = true })
  hi('@comment.documentation', { fg = c.bg_subtle, italic = true })
  hi('@comment.error', { fg = c.red, italic = true })
  hi('@comment.warning', { fg = c.yellow, italic = true })
  hi('@comment.note', { fg = c.teal, italic = true })
  hi('@comment.todo', { fg = c.yellow, bold = true })
  hi('@punctuation.delimiter', { fg = c.fg_dim })
  hi('@punctuation.bracket', { fg = c.fg_dim })
  hi('@punctuation.special', { fg = c.sky })
  hi('@tag', { fg = c.mauve })
  hi('@tag.attribute', { fg = c.teal })
  hi('@tag.delimiter', { fg = c.fg_dim })
  hi('@markup.heading', { fg = c.mauve, bold = true })
  hi('@markup.link', { fg = c.blue, underline = true })
  hi('@markup.link.url', { fg = c.teal, underline = true })
  hi('@markup.raw', { fg = c.teal })
  hi('@markup.italic', { italic = true })
  hi('@markup.strong', { bold = true })
  hi('@markup.list', { fg = c.mauve })
  hi('@diff.plus', { fg = c.green })
  hi('@diff.minus', { fg = c.red })
  hi('@diff.delta', { fg = c.yellow })
  hi('@module', { fg = c.fg_alt })
  hi('@namespace', { fg = c.fg_alt })
  hi('@label', { fg = c.mauve })

  -- ─── LSP semantic tokens (language-agnostic) ──────────────────────────────
  hi('@lsp.type.class', { fg = c.yellow })
  hi('@lsp.type.decorator', { fg = c.peach })
  hi('@lsp.type.enum', { fg = c.yellow })
  hi('@lsp.type.enumMember', { fg = c.peach })
  hi('@lsp.type.function', { fg = c.blue })
  hi('@lsp.type.interface', { fg = c.yellow })
  hi('@lsp.type.macro', { fg = c.pink })
  hi('@lsp.type.method', { fg = c.blue })
  hi('@lsp.type.namespace', { fg = c.fg_alt })
  hi('@lsp.type.parameter', { fg = c.red })
  hi('@lsp.type.property', { fg = c.fg_alt })
  hi('@lsp.type.struct', { fg = c.yellow })
  hi('@lsp.type.type', { fg = c.yellow })
  hi('@lsp.type.typeParameter', { fg = c.yellow })
  hi('@lsp.type.lifetime', { fg = c.peach })
  hi('@lsp.type.builtinType', { fg = c.yellow })
  -- cleared: TS handles these with finer granularity
  hi('@lsp.type.variable', {})
  hi('@lsp.type.selfKeyword', {})
  hi('@lsp.type.keyword', {})
  hi('@lsp.type.operator', {})
  hi('@lsp.type.string', {})
  hi('@lsp.type.number', {})
  hi('@lsp.type.boolean', {})
  hi('@lsp.type.comment', {})
  hi('@lsp.mod.static', { fg = c.red })
  hi('@lsp.mod.deprecated', { fg = c.fg_dim, strikethrough = true })
  hi('@lsp.mod.documentation', { fg = c.bg_subtle, italic = true })
  hi('@lsp.mod.defaultLibrary', { fg = c.yellow })
  hi('@lsp.typemod.function.declaration', { fg = c.blue })
  hi('@lsp.typemod.method.defaultLibrary', { fg = c.yellow })

  -- ── Rust ──────────────────────────────────────────────────────────────────
  hi('@lsp.type.namespace.rust', { fg = c.fg_alt })
  hi('@lsp.type.enum.rust', { fg = c.yellow })
  hi('@lsp.type.enumMember.rust', { fg = c.peach })
  hi('@lsp.type.struct.rust', { fg = c.yellow })
  hi('@lsp.type.interface.rust', { fg = c.yellow, italic = true })
  hi('@lsp.type.typeParameter.rust', { fg = c.yellow, italic = true })
  hi('@lsp.type.formatSpecifier.rust', { fg = c.red, italic = true })
  hi('@lsp.type.macro.rust', { fg = c.pink })
  hi('@lsp.type.function.rust', { fg = c.blue })
  hi('@lsp.type.method.rust', { fg = c.blue })
  hi('@lsp.type.lifetime.rust', { fg = c.peach, italic = true })
  hi('@lsp.type.selfKeyword.rust', { fg = c.red })
  hi('@lsp.type.parameter.rust', { fg = c.red })
  hi('@lsp.type.property.rust', { fg = c.fg_alt })
  hi('@lsp.mod.static.rust', { fg = c.red })
  hi('@lsp.mod.unsafe.rust', { fg = c.red, italic = true })
  hi('@lsp.mod.deprecated.rust', { fg = c.fg_dim, strikethrough = true })
  hi('@lsp.typemod.function.static.rust', { fg = c.blue })
  hi('@lsp.typemod.function.associated.rust', { fg = c.blue })
  hi('@lsp.typemod.method.static.rust', { fg = c.blue })
  hi('@lsp.typemod.variable.static.rust', { fg = c.red })
  hi('@lsp.typemod.variable.readonly.rust', { fg = c.peach })
  hi('@lsp.typemod.variable.mutable.rust', { fg = c.fg, underline = true })
  hi('@lsp.typemod.struct.readonly.rust', { fg = c.yellow })
  hi('@lsp.typemod.macro.unsafe.rust', { fg = c.pink, italic = true })

  -- ── Go ─────────────────────────────────────────────────────────────────────
  hi('@lsp.type.namespace.go', { fg = c.fg_alt })
  hi('@lsp.type.function.go', { fg = c.blue })
  hi('@lsp.type.method.go', { fg = c.blue })
  hi('@lsp.type.struct.go', { fg = c.yellow })
  hi('@lsp.type.interface.go', { fg = c.yellow, italic = true })
  hi('@lsp.type.typeParameter.go', { fg = c.yellow, italic = true })
  hi('@lsp.type.variable.go', { fg = c.fg })
  hi('@lsp.type.parameter.go', { fg = c.red })
  hi('@lsp.type.property.go', { fg = c.fg_alt })
  hi('@lsp.type.macro.go', { fg = c.pink })
  hi('@lsp.mod.static.go', { fg = c.red })
  hi('@lsp.mod.deprecated.go', { fg = c.fg_dim, strikethrough = true })
  hi('@lsp.typemod.function.exported.go', { fg = c.blue, bold = true })
  hi('@lsp.typemod.method.exported.go', { fg = c.blue, bold = true })
  hi('@lsp.typemod.type.exported.go', { fg = c.yellow, bold = true })
  hi('@lsp.typemod.variable.exported.go', { fg = c.fg, bold = true })

  -- ── C ───────────────────────────────────────────────────────────────────────
  hi('@lsp.type.function.c', { fg = c.blue })
  hi('@lsp.type.method.c', { fg = c.blue })
  hi('@lsp.type.struct.c', { fg = c.yellow })
  hi('@lsp.type.enum.c', { fg = c.yellow })
  hi('@lsp.type.enumMember.c', { fg = c.peach })
  hi('@lsp.type.macro.c', { fg = c.pink })
  hi('@lsp.type.type.c', { fg = c.yellow })
  hi('@lsp.type.parameter.c', { fg = c.red })
  hi('@lsp.type.variable.c', { fg = c.fg })
  hi('@lsp.type.property.c', { fg = c.fg_alt })
  hi('@lsp.mod.static.c', { fg = c.red })
  hi('@lsp.mod.deprecated.c', { fg = c.fg_dim, strikethrough = true })
  hi('@lsp.typemod.function.static.c', { fg = c.blue })
  hi('@lsp.typemod.variable.static.c', { fg = c.red })
  hi('@lsp.typemod.variable.readonly.c', { fg = c.peach })
  hi('@lsp.typemod.macro.globalScope.c', { fg = c.pink, bold = true })

  -- ── C++ ─────────────────────────────────────────────────────────────────────
  hi('@lsp.type.namespace.cpp', { fg = c.fg_alt })
  hi('@lsp.type.class.cpp', { fg = c.yellow })
  hi('@lsp.type.struct.cpp', { fg = c.yellow })
  hi('@lsp.type.enum.cpp', { fg = c.yellow })
  hi('@lsp.type.enumMember.cpp', { fg = c.peach })
  hi('@lsp.type.function.cpp', { fg = c.blue })
  hi('@lsp.type.method.cpp', { fg = c.blue })
  hi('@lsp.type.macro.cpp', { fg = c.pink })
  hi('@lsp.type.property.cpp', { fg = c.fg_alt })
  hi('@lsp.type.parameter.cpp', { fg = c.red })
  hi('@lsp.type.type.cpp', { fg = c.yellow })
  hi('@lsp.type.interface.cpp', { fg = c.yellow, italic = true })
  hi('@lsp.type.typeParameter.cpp', { fg = c.yellow, italic = true })
  hi('@lsp.mod.static.cpp', { fg = c.red })
  hi('@lsp.mod.virtual.cpp', { fg = c.blue, italic = true })
  hi('@lsp.mod.abstract.cpp', { fg = c.yellow, italic = true })
  hi('@lsp.mod.deprecated.cpp', { fg = c.fg_dim, strikethrough = true })
  hi('@lsp.typemod.method.static.cpp', { fg = c.blue })
  hi('@lsp.typemod.method.virtual.cpp', { fg = c.blue, italic = true })
  hi('@lsp.typemod.function.static.cpp', { fg = c.blue })
  hi('@lsp.typemod.function.virtual.cpp', { fg = c.blue, italic = true })
  hi('@lsp.typemod.variable.static.cpp', { fg = c.red })
  hi('@lsp.typemod.variable.readonly.cpp', { fg = c.peach })
  hi('@lsp.typemod.type.abstract.cpp', { fg = c.yellow, italic = true })
  hi('@lsp.typemod.macro.globalScope.cpp', { fg = c.pink, bold = true })
  hi(
    '@lsp.typemod.enumMember.defaultLibrary.cpp',
    { fg = c.red, italic = true }
  )
  -- Re-applied for cpp (LSP is primary highlighter at priority 999)
  hi('@lsp.type.variable.cpp', { fg = c.fg })
  hi('@lsp.type.keyword.cpp', { fg = c.mauve })
  hi('@lsp.type.operator.cpp', { fg = c.sky })
  hi('@lsp.type.string.cpp', { fg = c.teal })
  hi('@lsp.type.number.cpp', { fg = c.peach })
  hi('@lsp.type.boolean.cpp', { fg = c.peach })
  hi('@lsp.type.comment.cpp', { fg = c.fg_dim, italic = true })

  -- ── Java ─────────────────────────────────────────────────────────────────────
  hi('@lsp.type.namespace.java', { fg = c.fg_alt })
  hi('@lsp.type.class.java', { fg = c.yellow })
  hi('@lsp.type.interface.java', { fg = c.yellow, italic = true })
  hi('@lsp.type.enum.java', { fg = c.yellow })
  hi('@lsp.type.enumMember.java', { fg = c.peach })
  hi('@lsp.type.annotation.java', { fg = c.peach, italic = true })
  hi('@lsp.type.typeParameter.java', { fg = c.yellow, italic = true })
  hi('@lsp.type.function.java', { fg = c.blue })
  hi('@lsp.type.method.java', { fg = c.blue })
  hi('@lsp.type.property.java', { fg = c.fg_alt })
  hi('@lsp.type.parameter.java', { fg = c.red })
  hi('@lsp.type.variable.java', { fg = c.fg })
  hi('@lsp.type.macro.java', { fg = c.pink })
  hi('@lsp.mod.static.java', { fg = c.red })
  hi('@lsp.mod.abstract.java', { fg = c.yellow, italic = true })
  hi('@lsp.mod.deprecated.java', { fg = c.fg_dim, strikethrough = true })
  hi('@lsp.typemod.method.static.java', { fg = c.blue })
  hi('@lsp.typemod.method.abstract.java', { fg = c.blue, italic = true })
  hi('@lsp.typemod.class.abstract.java', { fg = c.yellow, italic = true })
  hi('@lsp.typemod.property.static.java', { fg = c.red, italic = true })
  hi('@lsp.typemod.variable.static.java', { fg = c.red })
  hi('@lsp.typemod.variable.readonly.java', { fg = c.peach })
  hi(
    '@lsp.typemod.variable.static.readonly.java',
    { fg = c.peach, bold = true }
  )

  -- ── Zig ──────────────────────────────────────────────────────────────────────
  hi('@lsp.type.namespace.zig', { fg = c.fg_alt })
  hi('@lsp.type.type.zig', { fg = c.yellow })
  hi('@lsp.type.struct.zig', { fg = c.yellow })
  hi('@lsp.type.enum.zig', { fg = c.yellow })
  hi('@lsp.type.enumMember.zig', { fg = c.peach })
  hi('@lsp.type.union.zig', { fg = c.yellow })
  hi('@lsp.type.tagField.zig', { fg = c.peach })
  hi('@lsp.type.field.zig', { fg = c.fg_alt })
  hi('@lsp.type.errorTag.zig', { fg = c.red })
  hi('@lsp.type.function.zig', { fg = c.blue })
  hi('@lsp.type.method.zig', { fg = c.blue })
  hi('@lsp.type.parameter.zig', { fg = c.red })
  hi('@lsp.type.variable.zig', { fg = c.fg })
  hi('@lsp.type.typeParameter.zig', { fg = c.yellow, italic = true })
  hi('@lsp.type.builtin.zig', { fg = c.sky })
  hi('@lsp.type.keyword.zig', { fg = c.mauve })
  hi('@lsp.type.operator.zig', { fg = c.sky })
  hi('@lsp.type.number.zig', { fg = c.peach })
  hi('@lsp.type.string.zig', { fg = c.teal })
  hi('@lsp.type.comment.zig', { fg = c.fg_dim, italic = true })
  hi('@lsp.type.decorator.zig', { fg = c.peach })
  hi('@lsp.mod.generic.zig', { fg = c.yellow, italic = true })
  hi('@lsp.mod.comptime.zig', { fg = c.mauve, italic = true })
  hi('@type.zig', { fg = c.yellow })
  hi('@type.builtin.zig', { fg = c.yellow })
  hi('@variable.parameter.zig', { fg = c.maroon })
  hi('@keyword.import.zig', { fg = c.mauve })
  hi('@function.builtin.zig', { fg = c.sky })
  hi('@string.special.zig', { fg = c.peach })

  -- Meson
  hi('@variable.meson', { fg = c.yellow })
  hi('@lsp.type.function.meson', { fg = c.blue })
  hi('@lsp.type.method.meson', { fg = c.blue })
  hi('@lsp.type.variable.meson', { fg = c.fg })
  hi('@lsp.typemod.variable.readonly.meson', { fg = c.sky })
  hi('@lsp.type.substitute_bounds.meson', { fg = c.fg_dim })
  hi('@lsp.type.keyword.meson', { fg = c.mauve })
  hi('@lsp.type.string.meson', { fg = c.teal })
  hi('@lsp.type.number.meson', { fg = c.peach })

  -- ─── LSP cross-language ──────────────────────────────────────────────────
  hi('LspReferenceText', { bg = c.bg_sel, nocombine = true })
  hi('LspReferenceRead', { bg = c.bg_sel })
  hi('LspReferenceWrite', { bg = c.bg_sel, underline = true })
  hi(
    'LspInlayHint',
    { fg = c.fg_dim, bg = c.bg_dark, italic = true, nocombine = true }
  )
  hi('LspCodeLens', { fg = c.fg_dim, italic = true })
  hi('LspSignatureActiveParameter', { fg = c.peach, bold = true })

  -- ─── Diagnostics ──────────────────────────────────────────────────────────
  hi('DiagnosticError', { fg = c.red })
  hi('DiagnosticWarn', { fg = c.yellow })
  hi('DiagnosticInfo', { fg = c.teal })
  hi('DiagnosticHint', { fg = c.sky })
  hi('DiagnosticOk', { fg = c.green })
  hi('DiagnosticUnnecessary', { fg = c.fg_dim })
  hi('DiagnosticDeprecated', { fg = c.fg_dim, strikethrough = true })
  hi('DiagnosticUnderlineError', { sp = c.red, undercurl = true })
  hi('DiagnosticUnderlineWarn', { sp = c.yellow, undercurl = true })
  hi('DiagnosticUnderlineInfo', { sp = c.teal, undercurl = true })
  hi('DiagnosticUnderlineHint', { sp = c.sky, undercurl = true })
  hi('DiagnosticVirtualTextError', { fg = c.red, bg = c.bg, italic = true })
  hi('DiagnosticVirtualTextWarn', { fg = c.yellow, bg = c.bg, italic = true })
  hi('DiagnosticVirtualTextInfo', { fg = c.teal, bg = c.bg, italic = true })
  hi('DiagnosticVirtualTextHint', { fg = c.sky, bg = c.bg, italic = true })
  hi('DiagnosticSignError', { fg = c.red })
  hi('DiagnosticSignWarn', { fg = c.yellow })
  hi('DiagnosticSignInfo', { fg = c.teal })
  hi('DiagnosticSignHint', { fg = c.sky })

  -- ─── Fidget ───────────────────────────────────────────────────────────────
  hi('FidgetTitle', { fg = p.overlay1, bg = p.mantle })
  hi('FidgetTask', { fg = p.overlay0, bg = p.mantle })
  hi('FidgetBorder', { fg = c.bg_sel })

  -- ─── Gitsigns ─────────────────────────────────────────────────────────────
  hi('GitSignsAdd', { fg = c.green })
  hi('GitSignsChange', { fg = c.yellow })
  hi('GitSignsDelete', { fg = c.red })
  hi('GitSignsAddNr', { fg = c.green })
  hi('GitSignsChangeNr', { fg = c.yellow })
  hi('GitSignsDeleteNr', { fg = c.red })
  hi('GitSignsCurrentLineBlame', { fg = c.fg_dim, italic = true })
  hi('GitSignsStagedAdd', { fg = c.teal })
  hi('GitSignsStagedChange', { fg = c.yellow })
  hi('GitSignsStagedDelete', { fg = c.red })
  hi('GitSignsAddInline', { bg = c.green, fg = c.bg })
  hi('GitSignsChangeInline', { bg = c.yellow, fg = c.bg })
  hi('GitSignsDeleteInline', { bg = c.red, fg = c.bg })

  -- ─── NeoTree ─────────────────────────────────────────────────────────────
  hi('NeoTreeGitAdded', { fg = c.green })
  hi('NeoTreeGitConflict', { fg = c.yellow })
  hi('NeoTreeGitDeleted', { fg = c.red })
  hi('NeoTreeGitIgnored', { fg = c.fg_dim, italic = true })
  hi('NeoTreeGitModified', { fg = c.peach })
  hi('NeoTreeGitRenamed', { fg = c.blue })
  hi('NeoTreeGitStaged', { fg = c.teal, italic = true })
  hi('NeoTreeGitUnstaged', { fg = c.yellow })
  hi('NeoTreeGitUntracked', { fg = c.flamingo })

  -- ─── Telescope ────────────────────────────────────────────────────────────
  hi('TelescopeNormal', { fg = c.fg, bg = c.bg_dark })
  hi('TelescopeBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('TelescopeTitle', { fg = c.mauve, bold = true })
  hi('TelescopePromptNormal', { bg = c.bg })
  hi('TelescopePromptBorder', { fg = c.bg_sel, bg = c.bg })
  hi('TelescopePromptTitle', { fg = c.yellow, bg = c.bg_dark })
  hi('TelescopePromptPrefix', { fg = c.mauve, bg = c.bg })
  hi('TelescopePromptCounter', { fg = c.fg_dim, bg = c.bg_sel })
  hi('TelescopeResultsNormal', { bg = c.bg_dark })
  hi('TelescopeResultsBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('TelescopeResultsTitle', { fg = c.bg_dark, bg = c.bg_dark })
  hi('TelescopePreviewNormal', { bg = c.bg })
  hi('TelescopePreviewBorder', { fg = c.bg_sel, bg = c.bg })
  hi('TelescopePreviewTitle', { fg = c.bg, bg = c.green })
  hi('TelescopeSelection', { fg = c.fg, bg = c.bg_sel })
  hi('TelescopeSelectionCaret', { fg = c.mauve, bg = c.bg_sel })
  hi('TelescopeMatching', { fg = c.yellow, bold = true })

  -- ─── Trouble ──────────────────────────────────────────────────────────────
  hi('TroubleNormal', { fg = c.fg, bg = c.bg_dark })
  hi('TroubleNormalNC', { fg = c.fg_alt, bg = c.bg_dark })
  hi('TroubleCount', { fg = c.mauve, bg = c.bg_sel, bold = true })
  hi('TroubleFilename', { fg = c.blue })
  hi('TroubleDirectory', { fg = c.blue })
  hi('TroublePos', { fg = c.fg_dim })
  hi('TroubleSource', { fg = c.fg_dim })
  hi('TroubleCode', { fg = c.fg_dim })
  hi('TroubleText', { fg = c.fg })
  hi('TroubleIndent', { fg = c.bg_sel })
  hi('TroubleIndentFoldClosed', { fg = c.mauve })
  hi('TroubleIndentFoldOpen', { fg = c.fg_dim })
  hi('TroublePreview', { bg = c.bg_sel })

  -- ─── Which-key ────────────────────────────────────────────────────────────
  hi('WhichKey', { fg = c.mauve })
  hi('WhichKeyGroup', { fg = c.teal })
  hi('WhichKeyDesc', { fg = c.fg_alt })
  hi('WhichKeySeparator', { fg = c.fg_dim })
  hi('WhichKeyValue', { fg = c.fg_dim })
  hi('WhichKeyBorder', { fg = c.bg_sel })
  hi('WhichKeyNormal', { bg = c.bg_dark })

  -- ─── Mini ─────────────────────────────────────────────────────────────────
  hi('MiniFilesNormal', { fg = c.fg, bg = c.bg_dark })
  hi('MiniFilesTitle', { fg = c.mauve, bold = true })
  hi('MiniFilesTitleFocused', { fg = c.bg, bg = c.mauve, bold = true })
  hi('MiniFilesBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('MiniFilesBorderModified', { fg = c.yellow, bg = c.bg_dark })
  hi('MiniFilesCursorLine', { bg = c.bg_sel })
  hi('MiniFilesDirectory', { fg = c.blue })
  hi('MiniIndentscopeSymbol', { fg = c.bg_sel })
  hi('MiniIndentscopePrefix', { fg = c.bg_sel })
  hi('MiniTablineCurrent', { fg = c.lavender, bg = c.bg, bold = true })
  hi('MiniTablineVisible', { fg = c.fg_alt, bg = c.bg_dark })
  hi('MiniTablineHidden', { fg = c.fg_dim, bg = c.bg })
  hi('MiniTablineModifiedCurrent', { fg = c.yellow, bg = c.bg, bold = true })
  hi('MiniTablineModifiedVisible', { fg = c.yellow, bg = c.bg_dark })
  hi('MiniTablineModifiedHidden', { fg = c.fg_dim, bg = c.bg })
  hi('MiniTablineFill', { bg = c.bg })
  hi('MiniSurround', { fg = c.bg, bg = c.peach, bold = true })

  -- ─── Rainbow delimiters ───────────────────────────────────────────────────
  hi('RainbowDelimiterViolet', { fg = c.mauve })
  hi('RainbowDelimiterCyan', { fg = c.teal })
  hi('RainbowDelimiterBlue', { fg = c.blue })
  hi('RainbowDelimiterYellow', { fg = c.yellow })
  hi('RainbowDelimiterRed', { fg = c.red })
  hi('RainbowDelimiterOrange', { fg = c.peach })
  hi('RainbowDelimiterGreen', { fg = c.green })

  hi('@property.ron', { link = 'Identifier' })
  hi('@string.ron', { link = 'String' })
  hi('@number.ron', { link = 'Number' })
  hi('@boolean.ron', { link = 'Boolean' })
  hi('@constructor.ron', { link = 'Type' })
  hi('@punctuation.bracket.ron', { link = 'Delimiter' })
  hi('@punctuation.delimiter.ron', { link = 'Delimiter' })

  -- ─── Todo-comments ────────────────────────────────────────────────────────
  hi('TodoBgTODO', { fg = c.bg, bg = c.blue, bold = true })
  hi('TodoBgFIX', { fg = c.bg, bg = c.red, bold = true })
  hi('TodoBgHACK', { fg = c.bg, bg = c.yellow, bold = true })
  hi('TodoBgWARN', { fg = c.bg, bg = c.yellow, bold = true })
  hi('TodoBgPERF', { fg = c.bg, bg = c.mauve, bold = true })
  hi('TodoBgNOTE', { fg = c.bg, bg = c.teal, bold = true })
  hi('TodoBgTEST', { fg = c.bg, bg = c.sky, bold = true })
  hi('TodoFgTODO', { fg = c.blue })
  hi('TodoFgFIX', { fg = c.red })
  hi('TodoFgHACK', { fg = c.yellow })
  hi('TodoFgWARN', { fg = c.yellow })
  hi('TodoFgPERF', { fg = c.mauve })
  hi('TodoFgNOTE', { fg = c.teal })
  hi('TodoFgTEST', { fg = c.sky })

  -- dropbar
  hi('DropBarCurrentContext', { bg = c.bg_dark })
  hi('DropBarMenuCurrentContext', { bg = c.bg_dark })
  hi('DropBarMenuNormalFloat', { fg = c.fg, bg = c.bg_dark })
  hi('DropBarMenuFloatBorder', { fg = c.bg_sel, bg = c.bg_dark })
  hi('DropBarHover', { fg = c.bg_sel, bg = c.bg_dark })
  hi('DropBarPreview', { bg = c.bg_dark })
  hi('DropBarIconKindDefault', { fg = c.mauve })
  hi('DropBarKindDefault', { fg = c.fg_alt })

  -- smart-splits
  hi('SmartSplitsMove', { fg = c.teal, bold = true })
  hi('SmartSplitsResize', { fg = c.yellow, bold = true })

  -- bufferline
  hi('BufferLineFill', { bg = c.bg_dark })
  hi('BufferLineBackground', { fg = p.overlay0, bg = c.bg_dark })
  hi('BufferLineBufferVisible', { fg = p.surface0, bg = c.bg_dark })
  hi(
    'BufferLineBufferSelected',
    { fg = c.fg, bg = c.bg_dark, bold = true, italic = true }
  )
  hi('BufferLineNumbers', { fg = c.overlay0, bg = c.bg_dark })
  hi('BufferLineNumbersSelected', { fg = c.fg, bg = c.bg_dark, bold = true })
  hi('BufferLineModified', { fg = p.overlay0, bg = c.bg_dark })
  hi(
    'BufferLineModifiedSelected',
    { fg = c.yellow, bg = c.bg_dark, bold = true }
  )
  hi('BufferLineIndicatorSelected', { fg = c.mauve, bg = c.bg_dark })
  hi('BufferLineDuplicate', { fg = p.overlay2, bg = c.bg_dark, italic = true })
  hi(
    'BufferLineDuplicateSelected',
    { fg = p.overlay2, bg = c.bg_dark, italic = true }
  )
  hi(
    'BufferLineDuplicateVisible',
    { fg = p.overlay2, bg = c.bg_dark, italic = true }
  )
  hi('BufferLineSeparator', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BufferLineSeparatorSelected', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BufferLineSeparatorVisible', { fg = c.bg_sel, bg = c.bg_dark })
  hi('BufferLineOffsetSeparator', { fg = c.bg_dark, bg = c.bg_dark })

  -- render-markdown
  hi('RenderMarkdownH1', { fg = c.mauve, bold = true })
  hi('RenderMarkdownH2', { fg = c.blue, bold = true })
  hi('RenderMarkdownH3', { fg = c.teal, bold = true })
  hi('RenderMarkdownH4', { fg = c.yellow, bold = true })
  hi('RenderMarkdownH5', { fg = c.green, bold = true })
  hi('RenderMarkdownH6', { fg = c.sky, bold = true })
  hi('RenderMarkdownH1Bg', { bg = c.bg_sel })
  hi('RenderMarkdownH2Bg', { bg = c.bg_sel })
  hi('RenderMarkdownH3Bg', { bg = c.bg_sel })
  hi('RenderMarkdownH4Bg', { bg = c.bg_sel })
  hi('RenderMarkdownH5Bg', { bg = c.bg_sel })
  hi('RenderMarkdownH6Bg', { bg = c.bg_sel })
  hi('RenderMarkdownCode', { bg = c.bg_dark })
  hi('RenderMarkdownCodeInline', { fg = c.teal, bg = c.bg_sel })
  hi('RenderMarkdownBullet', { fg = c.mauve })
  hi('RenderMarkdownChecked', { fg = c.green })
  hi('RenderMarkdownUnchecked', { fg = c.fg_dim })
  hi('RenderMarkdownTodo', { fg = c.yellow })
  hi('RenderMarkdownTableHead', { fg = c.mauve, bold = true })
  hi('RenderMarkdownTableRow', { fg = c.fg_alt })
  hi('RenderMarkdownTableFill', { fg = c.bg_sel })
  hi('RenderMarkdownDash', { fg = c.bg_sel })
  hi('RenderMarkdownLink', { fg = c.blue, underline = true })
  hi('RenderMarkdownWikiLink', { fg = c.teal, underline = true })
  hi('RenderMarkdownQuote', { fg = c.fg_dim, italic = true })

  -- ─── Toggleterm ───────────────────────────────────────────────────────────
  hi('ToggleTerm1FloatBorder', { fg = c.bg_sel })
  hi('ToggleTermNormal', { bg = c.bg })

  -- ─── Mason ────────────────────────────────────────────────────────────────
  hi('MasonNormal', { bg = c.bg_dark })
  hi('MasonHeader', { fg = c.bg, bg = c.mauve, bold = true })
  hi('MasonHeaderSecondary', { fg = c.bg, bg = c.teal, bold = true })
  hi('MasonHighlight', { fg = c.teal })
  hi('MasonHighlightBlock', { fg = c.bg, bg = c.teal })
  hi('MasonHighlightBlockBold', { fg = c.bg, bg = c.teal, bold = true })
  hi('MasonMuted', { fg = c.fg_dim })
  hi('MasonMutedBlock', { fg = c.bg, bg = c.bg_sel })
  hi('MasonError', { fg = c.red })
  hi('MasonWarning', { fg = c.yellow })
  hi('MasonLink', { fg = c.blue, underline = true })

  -- ─── Syntax-aware cursor ─────────────────────────────────────────────────
  local fallback_fg = c.fg

  local function resolve_fg(name)
    local seen, cur = {}, name
    for _ = 1, 8 do
      if seen[cur] then
        break
      end
      seen[cur] = true
      local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = cur, link = true })
      if not ok or not hl then
        break
      end
      if hl.fg then
        return string.format('#%06x', hl.fg)
      end
      if hl.link then
        cur = hl.link
      else
        break
      end
    end
  end

  local function capture_specificity(name)
    local n = 0
    for _ in name:gmatch('%.') do
      n = n + 1
    end
    return n
  end

  local function get_highest_priority_fg(buf, row, col)
    local candidates = {}
    local ok, marks = pcall(
      vim.api.nvim_buf_get_extmarks,
      buf,
      -1,
      { row, col },
      { row, col + 1 },
      { details = true, hl_name = true, overlap = true }
    )
    if ok then
      for _, mark in ipairs(marks) do
        local d = mark[4]
        if d and d.hl_group and d.priority then
          table.insert(
            candidates,
            { group = d.hl_group, priority = d.priority }
          )
        end
      end
    end
    local ts_ok, captures =
      pcall(vim.treesitter.get_captures_at_pos, buf, row, col)
    if ts_ok then
      for _, cap in ipairs(captures) do
        local n = '@' .. cap.capture
        local ln = n .. '.' .. (cap.lang or '')
        local sp = 100 + capture_specificity(cap.capture)
        table.insert(candidates, { group = ln, priority = sp + 0.5 })
        table.insert(candidates, { group = n, priority = sp })
      end
    end
    local syn_id = vim.fn.synID(row + 1, col + 1, true)
    if syn_id ~= 0 then
      local sn = vim.fn.synIDattr(vim.fn.synIDtrans(syn_id), 'name')
      if sn and sn ~= '' then
        table.insert(candidates, { group = sn, priority = 50 })
      end
    end
    table.sort(candidates, function(a, b)
      return a.priority > b.priority
    end)
    for _, cand in ipairs(candidates) do
      local fg = resolve_fg(cand.group)
      if fg then
        return fg
      end
    end
  end

  vim.o.updatetime = 120
  vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
    desc = 'Syntax-aware cursor colour',
    callback = function()
      local buf = vim.api.nvim_get_current_buf()
      local row, col = unpack(vim.api.nvim_win_get_cursor(0))
      local fg = get_highest_priority_fg(buf, row - 1, col)
      vim.api.nvim_set_hl(0, 'Cursor', { fg = c.bg, bg = fg or fallback_fg })
    end,
  })
end

vim.hl.priorities.semantic_tokens = 999

M.load()

if M.transparent then
  apply_transparent(true)
end

vim.api.nvim_create_autocmd('ColorScheme', {
  pattern = 'wallpaper',
  desc = 'wallpaper: restore transparency on reload',
  callback = function()
    if M.transparent then
      apply_transparent(true)
    end
  end,
})

vim.keymap.set('n', '<leader>tm', function()
  M.toggle_transparent()
end, { desc = 'wallpaper: toggle transparency', silent = true })

package.preload['dankula'] = function() return M end
return M
