local M = {}

-- Java keyword documentation in jdtls style
local help_text = {
  -- Keywords
  ['enum'] = {
    lines = {
      "enum",
      "",
      "Declares an enumeration type - a special class that represents a fixed set of constants.",
      "",
      "Enums are type-safe and can have fields, methods, and constructors. Each constant is",
      "an instance of the enum type. Enums implicitly extend java.lang.Enum and cannot extend",
      "other classes, but can implement interfaces.",
      "",
      "Basic enum:",
      "public enum Color {",
      "    RED, GREEN, BLUE",
      "}",
      "",
      "Enum with fields and methods:",
      "public enum Planet {",
      "    EARTH(5.976e+24, 6.37814e6),",
      "    MARS(6.421e+23, 3.3972e6);",
      "    ",
      "    private final double mass;",
      "    private final double radius;",
      "    ",
      "    Planet(double mass, double radius) {",
      "        this.mass = mass;",
      "        this.radius = radius;",
      "    }",
      "    ",
      "    public double surfaceGravity() {",
      "        return 6.67300E-11 * mass / (radius * radius);",
      "    }",
      "}",
    },
    code_start = 9,
    code_end = 29,
  },

  ['class'] = {
    lines = {
      "class",
      "",
      "Defines a class - the fundamental building block of object-oriented programming in Java.",
      "",
      "A class is a blueprint for creating objects. It encapsulates data (fields) and behavior",
      "(methods). Classes support inheritance, polymorphism, and encapsulation. Every Java",
      "application must have at least one class with a main() method as the entry point.",
      "",
      "Basic class:",
      "public class Person {",
      "    private String name;",
      "    private int age;",
      "    ",
      "    public Person(String name, int age) {",
      "        this.name = name;",
      "        this.age = age;",
      "    }",
      "    ",
      "    public String getName() {",
      "        return name;",
      "    }",
      "    ",
      "    public void setName(String name) {",
      "        this.name = name;",
      "    }",
      "}",
    },
    code_start = 9,
    code_end = 25,
  },

  ['interface'] = {
    lines = {
      "interface",
      "",
      "Defines a contract that classes must implement. Interfaces specify what methods a class",
      "must provide, but not how they should be implemented.",
      "",
      "Since Java 8, interfaces can contain default methods (with implementation) and static",
      "methods. Since Java 9, they can also have private methods. All methods in an interface",
      "are implicitly public and abstract (unless marked default or static). All fields are",
      "implicitly public, static, and final.",
      "",
      "Basic interface:",
      "public interface Drawable {",
      "    void draw();  // abstract method",
      "    void resize(int width, int height);",
      "}",
      "",
      "Interface with default method:",
      "public interface Vehicle {",
      "    void start();",
      "    ",
      "    default void stop() {",
      "        System.out.println(\"Vehicle stopped\");",
      "    }",
      "}",
    },
    code_start = 11,
    code_end = 24,
  },

  -- Access Modifiers
  ['public'] = {
    lines = {
      "public - Access Modifier",
      "",
      "The most permissive access level. Public members are accessible from anywhere in the",
      "application - from any class in any package.",
      "",
      "Use public for:",
      "  - Classes that need to be used by other packages",
      "  - Methods that form the public API of a class",
      "  - Constants that should be widely accessible",
      "",
      "Example:",
      "public class BankAccount {",
      "    public static final int MAX_BALANCE = 1000000;",
      "    ",
      "    public void deposit(double amount) {",
      "        // accessible from anywhere",
      "    }",
      "}",
    },
    code_start = 13,
    code_end = 20,
  },

  ['private'] = {
    lines = {
      "private - Access Modifier",
      "",
      "The most restrictive access level. Private members are only accessible within the",
      "same class where they are declared. This is the foundation of encapsulation.",
      "",
      "Use private for:",
      "  - Implementation details that should be hidden",
      "  - Fields that should only be accessed via getters/setters",
      "  - Helper methods used only within the class",
      "",
      "Best practice: Make fields private and provide public getters/setters as needed.",
      "",
      "Example:",
      "public class Person {",
      "    private String ssn;  // sensitive data",
      "    private int age;",
      "    ",
      "    private boolean isValid() {",
      "        return age >= 0;  // helper method",
      "    }",
      "    ",
      "    public int getAge() {",
      "        return age;",
      "    }",
      "}",
    },
    code_start = 13,
    code_end = 25,
  },

  ['protected'] = {
    lines = {
      "protected - Access Modifier",
      "",
      "Members are accessible within the same package AND by subclasses in any package.",
      "This is commonly used when you want subclasses to access or override functionality",
      "while keeping it hidden from unrelated classes.",
      "",
      "Use protected for:",
      "  - Methods that subclasses need to override or call",
      "  - Fields that subclasses need to access directly",
      "  - Internal APIs meant for inheritance hierarchies",
      "",
      "Example:",
      "public class Shape {",
      "    protected double area;",
      "    ",
      "    protected void calculateArea() {",
      "        // subclasses can override this",
      "    }",
      "}",
      "",
      "public class Circle extends Shape {",
      "    @Override",
      "    protected void calculateArea() {",
      "        area = Math.PI * radius * radius;",
      "    }",
      "}",
    },
    code_start = 13,
    code_end = 26,
  },

  -- Non-access Modifiers
  ['static'] = {
    lines = {
      "static - Modifier",
      "",
      "Indicates that a member belongs to the class itself rather than to instances of the class.",
      "Static members are shared among all instances and can be accessed without creating an object.",
      "",
      "Static fields:",
      "  - Shared by all instances (class variable)",
      "  - Initialized once when the class is loaded",
      "  - Often used with 'final' for constants",
      "",
      "Static methods:",
      "  - Can be called without an instance: ClassName.methodName()",
      "  - Cannot access instance variables or methods directly",
      "  - Cannot use 'this' keyword",
      "  - Common use: utility methods, factory methods",
      "",
      "Example:",
      "public class MathUtils {",
      "    public static final double PI = 3.14159;",
      "    private static int callCount = 0;",
      "    ",
      "    public static double square(double x) {",
      "        callCount++;",
      "        return x * x;",
      "    }",
      "    ",
      "    public static void main(String[] args) {",
      "        double result = MathUtils.square(5);  // no instance needed",
      "    }",
      "}",
    },
    code_start = 18,
    code_end = 31,
  },

  ['final'] = {
    lines = {
      "final - Modifier",
      "",
      "Prevents modification, extension, or overriding. The meaning depends on where it's applied.",
      "",
      "Final variables:",
      "  - Cannot be reassigned after initialization",
      "  - Must be initialized when declared or in constructor",
      "  - Naming convention: UPPER_CASE for static final constants",
      "",
      "Final methods:",
      "  - Cannot be overridden by subclasses",
      "  - Use when the method's behavior must not change",
      "",
      "Final classes:",
      "  - Cannot be extended (no subclasses allowed)",
      "  - Examples: String, Integer, Math",
      "",
      "Example:",
      "public final class ImmutablePoint {",
      "    private final int x;  // must be initialized",
      "    private final int y;",
      "    public static final int ORIGIN_X = 0;",
      "    ",
      "    public ImmutablePoint(int x, int y) {",
      "        this.x = x;  // can only set once",
      "        this.y = y;",
      "    }",
      "    ",
      "    public final int getX() {",
      "        return x;  // cannot be overridden (if class wasn't final)",
      "    }",
      "}",
    },
    code_start = 18,
    code_end = 32,
  },

  ['abstract'] = {
    lines = {
      "abstract - Modifier",
      "",
      "Declares incomplete types that must be completed by subclasses. Used to define common",
      "interfaces and partial implementations in inheritance hierarchies.",
      "",
      "Abstract classes:",
      "  - Cannot be instantiated directly (no 'new AbstractClass()')",
      "  - Can have both abstract and concrete methods",
      "  - Can have constructors (called by subclass constructors)",
      "  - Can have fields and static members",
      "  - Use when classes share common code but need customization",
      "",
      "Abstract methods:",
      "  - Have no body (just signature)",
      "  - Must be overridden by concrete subclasses",
      "  - Can only exist in abstract classes or interfaces",
      "",
      "Example:",
      "public abstract class Animal {",
      "    protected String name;",
      "    ",
      "    public Animal(String name) {",
      "        this.name = name;",
      "    }",
      "    ",
      "    public abstract void makeSound();  // must be implemented",
      "    ",
      "    public void sleep() {  // concrete method",
      "        System.out.println(name + \" is sleeping\");",
      "    }",
      "}",
      "",
      "public class Dog extends Animal {",
      "    public Dog(String name) {",
      "        super(name);",
      "    }",
      "    ",
      "    @Override",
      "    public void makeSound() {",
      "        System.out.println(\"Woof!\");",
      "    }",
      "}",
    },
    code_start = 18,
    code_end = 42,
  },

  ['synchronized'] = {
    lines = {
      "synchronized - Modifier",
      "",
      "Ensures thread-safe access to methods or code blocks. Only one thread can execute",
      "synchronized code at a time, preventing race conditions and data corruption.",
      "",
      "Synchronized methods:",
      "  - Lock the entire object (instance methods) or class (static methods)",
      "  - Simple but can reduce performance",
      "",
      "Synchronized blocks:",
      "  - Lock only a specific object",
      "  - More granular control over synchronization",
      "  - Better performance when only part of method needs synchronization",
      "",
      "Example:",
      "public class Counter {",
      "    private int count = 0;",
      "    private final Object lock = new Object();",
      "    ",
      "    // Synchronized method",
      "    public synchronized void increment() {",
      "        count++;",
      "    }",
      "    ",
      "    // Synchronized block (more flexible)",
      "    public void decrement() {",
      "        synchronized(lock) {",
      "            count--;",
      "        }",
      "    }",
      "}",
    },
    code_start = 15,
    code_end = 31,
  },

  ['volatile'] = {
    lines = {
      "volatile - Modifier",
      "",
      "Indicates that a variable's value may be modified by different threads. Ensures that:",
      "  - Reads always get the latest value from main memory (not cached)",
      "  - Writes are immediately visible to other threads",
      "  - Operations on the variable are not reordered by the compiler",
      "",
      "Use volatile for:",
      "  - Flags that signal status changes between threads",
      "  - Variables that are written by one thread and read by others",
      "",
      "Note: volatile does NOT provide atomicity for compound operations like count++.",
      "For that, use AtomicInteger or synchronized.",
      "",
      "Example:",
      "public class TaskRunner {",
      "    private volatile boolean running = true;",
      "    ",
      "    public void run() {",
      "        while (running) {  // always reads latest value",
      "            doWork();",
      "        }",
      "    }",
      "    ",
      "    public void stop() {",
      "        running = false;  // immediately visible to other threads",
      "    }",
      "}",
    },
    code_start = 15,
    code_end = 29,
  },

  ['transient'] = {
    lines = {
      "transient - Modifier",
      "",
      "Indicates that a field should be skipped during serialization. When an object is",
      "serialized, transient fields are not saved and will have default values when deserialized.",
      "",
      "Use transient for:",
      "  - Sensitive data (passwords, tokens) that shouldn't be persisted",
      "  - Derived/calculated values that can be recreated",
      "  - Cache data or temporary state",
      "  - Fields that reference non-serializable objects",
      "",
      "Example:",
      "public class User implements Serializable {",
      "    private static final long serialVersionUID = 1L;",
      "    ",
      "    private String username;",
      "    private transient String password;  // not saved during serialization",
      "    private transient int loginCount;   // can be recalculated",
      "    ",
      "    // After deserialization, password will be null, loginCount will be 0",
      "}",
    },
    code_start = 12,
    code_end = 21,
  },

  ['native'] = {
    lines = {
      "native - Modifier",
      "",
      "Indicates that a method is implemented in platform-specific code (usually C or C++)",
      "using the Java Native Interface (JNI). The method has no body in Java.",
      "",
      "Use cases:",
      "  - Access system-specific functionality",
      "  - Interface with existing C/C++ libraries",
      "  - Performance-critical operations",
      "  - Hardware interaction",
      "",
      "Note: Native methods break platform independence and can introduce security risks.",
      "",
      "Example:",
      "public class SystemInfo {",
      "    // Implementation is in C/C++ library",
      "    public native void getCpuInfo();",
      "    public native long getAvailableMemory();",
      "    ",
      "    static {",
      "        System.loadLibrary(\"systeminfo\");  // load native library",
      "    }",
      "}",
    },
    code_start = 14,
    code_end = 23,
  },

  -- Class Relationships
  ['extends'] = {
    lines = {
      "extends",
      "",
      "Establishes an inheritance relationship. The subclass inherits all accessible fields",
      "and methods from its superclass and can add new members or override existing ones.",
      "",
      "Key points:",
      "  - Java supports single inheritance only (one direct superclass)",
      "  - Subclass inherits all non-private members",
      "  - Use super() to call parent constructor",
      "  - Use super.method() to call overridden parent methods",
      "  - Constructors are not inherited",
      "",
      "Example:",
      "public class Animal {",
      "    protected String name;",
      "    ",
      "    public Animal(String name) {",
      "        this.name = name;",
      "    }",
      "    ",
      "    public void eat() {",
      "        System.out.println(name + \" is eating\");",
      "    }",
      "}",
      "",
      "public class Dog extends Animal {",
      "    private String breed;",
      "    ",
      "    public Dog(String name, String breed) {",
      "        super(name);  // must call parent constructor",
      "        this.breed = breed;",
      "    }",
      "    ",
      "    @Override",
      "    public void eat() {",
      "        super.eat();  // can call parent method",
      "        System.out.println(\"Dog is chomping\");",
      "    }",
      "}",
    },
    code_start = 13,
    code_end = 38,
  },

  ['implements'] = {
    lines = {
      "implements",
      "",
      "Declares that a class provides concrete implementations for all abstract methods",
      "defined in one or more interfaces. This is Java's way of achieving multiple inheritance",
      "of type (not implementation).",
      "",
      "Key points:",
      "  - A class can implement multiple interfaces (comma-separated)",
      "  - Must provide implementations for all interface methods",
      "  - Can implement methods with more permissive access (public)",
      "  - Enables polymorphism and loose coupling",
      "",
      "Example:",
      "public interface Drawable {",
      "    void draw();",
      "    void resize(int width, int height);",
      "}",
      "",
      "public interface Movable {",
      "    void move(int x, int y);",
      "}",
      "",
      "public class Circle implements Drawable, Movable {",
      "    private int x, y, radius;",
      "    ",
      "    @Override",
      "    public void draw() {",
      "        System.out.println(\"Drawing circle at (\" + x + \",\" + y + \")\");",
      "    }",
      "    ",
      "    @Override",
      "    public void resize(int width, int height) {",
      "        radius = Math.min(width, height) / 2;",
      "    }",
      "    ",
      "    @Override",
      "    public void move(int newX, int newY) {",
      "        this.x = newX;",
      "        this.y = newY;",
      "    }",
      "}",
    },
    code_start = 13,
    code_end = 42,
  },

  -- Exception Handling
  ['throw'] = {
    lines = {
      "throw",
      "",
      "Explicitly throws an exception.",
      "",
      "if (age < 0) {",
      "    throw new IllegalArgumentException(\"Age cannot be negative\");",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  ['throws'] = {
    lines = {
      "throws",
      "",
      "Declares that a method may throw one or more checked exceptions.",
      "",
      "public void readFile(String path) throws IOException {",
      "    // method implementation",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  ['try'] = {
    lines = {
      "try",
      "",
      "Begins an exception handling block. Code that may throw exceptions is placed here.",
      "",
      "try {",
      "    // code that may throw exception",
      "} catch (Exception e) {",
      "    // handle exception",
      "}",
    },
    code_start = 5,
    code_end = 9,
  },

  ['catch'] = {
    lines = {
      "catch",
      "",
      "Handles specific exceptions thrown in the try block.",
      "",
      "try {",
      "    // risky code",
      "} catch (IOException e) {",
      "    System.err.println(\"IO Error: \" + e.getMessage());",
      "}",
      "",
      "Note: Multiple catch blocks can handle different exception types.",
    },
    code_start = 5,
    code_end = 9,
  },

  ['finally'] = {
    lines = {
      "finally",
      "",
      "Always executes after try/catch blocks, regardless of whether an exception occurred.",
      "Typically used for cleanup operations.",
      "",
      "try {",
      "    // open resource",
      "} finally {",
      "    // close resource (always executed)",
      "}",
    },
    code_start = 6,
    code_end = 10,
  },

  -- Control Flow
  ['if'] = {
    lines = {
      "if",
      "",
      "Conditional statement that executes code if the condition evaluates to true.",
      "",
      "if (x > 0) {",
      "    System.out.println(\"Positive\");",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  ['else'] = {
    lines = {
      "else",
      "",
      "Provides an alternative branch when the if condition is false.",
      "",
      "if (x > 0) {",
      "    System.out.println(\"Positive\");",
      "} else {",
      "    System.out.println(\"Non-positive\");",
      "}",
    },
    code_start = 5,
    code_end = 9,
  },

  ['switch'] = {
    lines = {
      "switch",
      "",
      "Multi-way branch statement that selects one of many code blocks to execute.",
      "",
      "switch (day) {",
      "    case MONDAY:",
      "        System.out.println(\"Start of week\");",
      "        break;",
      "    case FRIDAY:\",",
      "        System.out.println(\"End of week\");",
      "        break;",
      "    default:",
      "        System.out.println(\"Midweek\");",
      "}",
    },
    code_start = 5,
    code_end = 14,
  },

  ['case'] = {
    lines = {
      "case",
      "",
      "Defines a branch in a switch statement.",
      "",
      "case 1:",
      "    doSomething();",
      "    break;",
    },
    code_start = 5,
    code_end = 7,
  },

  ['default'] = {
    lines = {
      "default",
      "",
      "Defines the default branch in a switch statement, executed when no case matches.",
      "",
      "default:",
      "    handleDefault();",
    },
    code_start = 5,
    code_end = 6,
  },

  ['for'] = {
    lines = {
      "for",
      "",
      "Loop with initialization, condition, and update expressions.",
      "",
      "for (int i = 0; i < 10; i++) {",
      "    System.out.println(i);",
      "}",
      "",
      "Enhanced for loop (for-each):",
      "for (String item : collection) {",
      "    System.out.println(item);",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  ['while'] = {
    lines = {
      "while",
      "",
      "Loop that executes while the condition is true. Checks condition before each iteration.",
      "",
      "while (i < 10) {",
      "    System.out.println(i);",
      "    i++;",
      "}",
    },
    code_start = 5,
    code_end = 8,
  },

  ['do'] = {
    lines = {
      "do",
      "",
      "Loop that executes at least once, then continues while the condition is true.",
      "",
      "do {",
      "    System.out.println(i);",
      "    i++;",
      "} while (i < 10);",
    },
    code_start = 5,
    code_end = 8,
  },

  ['break'] = {
    lines = {
      "break",
      "",
      "Exits from the innermost loop or switch statement.",
      "",
      "for (int i = 0; i < 10; i++) {",
      "    if (i == 5) break;",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  ['continue'] = {
    lines = {
      "continue",
      "",
      "Skips the rest of the current iteration and continues with the next iteration.",
      "",
      "for (int i = 0; i < 10; i++) {",
      "    if (i % 2 == 0) continue;",
      "    System.out.println(i);  // only odd numbers",
      "}",
    },
    code_start = 5,
    code_end = 8,
  },

  -- Return and Value
  ['void'] = {
    lines = {
      "void",
      "",
      "Indicates that a method does not return a value.",
      "",
      "public void printMessage() {",
      "    System.out.println(\"Hello\");",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  ['return'] = {
    lines = {
      "return",
      "",
      "Exits from the current method and optionally returns a value.",
      "",
      "public int sum(int a, int b) {",
      "    return a + b;",
      "}",
    },
    code_start = 5,
    code_end = 7,
  },

  -- Object Creation
  ['new'] = {
    lines = {
      "new",
      "",
      "Creates a new instance of a class (object) or array.",
      "",
      "MyClass obj = new MyClass();",
      "int[] array = new int[10];",
    },
    code_start = 5,
    code_end = 6,
  },

  ['this'] = {
    lines = {
      "this",
      "",
      "References the current object instance.",
      "",
      "Common uses:",
      "  - Distinguish instance variables from parameters",
      "  - Call other constructors",
      "  - Pass current object as parameter",
      "",
      "public MyClass(int value) {",
      "    this.value = value;  // distinguish field from parameter",
      "}",
    },
    code_start = 10,
    code_end = 12,
  },

  ['super'] = {
    lines = {
      "super",
      "",
      "References the parent class.",
      "",
      "Common uses:",
      "  - Call parent class constructor",
      "  - Access parent class methods",
      "  - Access parent class fields",
      "",
      "public class Dog extends Animal {",
      "    public Dog() {",
      "        super();  // call parent constructor",
      "    }",
      "}",
    },
    code_start = 10,
    code_end = 14,
  },

  -- Special Values
  ['null'] = {
    lines = {
      "null",
      "",
      "Represents the absence of an object reference.",
      "",
      "String str = null;",
      "if (obj == null) {",
      "    // handle null case",
      "}",
      "",
      "Note: Attempting to use null references causes NullPointerException.",
    },
    code_start = 5,
    code_end = 8,
  },

  ['true'] = {
    lines = {
      "true - boolean literal",
      "",
      "Represents the boolean value true.",
      "",
      "boolean flag = true;",
      "if (true) {",
      "    // always executes",
      "}",
    },
    code_start = 5,
    code_end = 8,
  },

  ['false'] = {
    lines = {
      "false - boolean literal",
      "",
      "Represents the boolean value false.",
      "",
      "boolean flag = false;",
      "if (false) {",
      "    // never executes",
      "}",
    },
    code_start = 5,
    code_end = 8,
  },

  -- Package and Import
  ['package'] = {
    lines = {
      "package",
      "",
      "Declares the package to which the class belongs.",
      "Must be the first statement in a Java file (except comments).",
      "",
      "package com.example.myapp;",
    },
    code_start = 6,
    code_end = 6,
  },

  ['import'] = {
    lines = {
      "import",
      "",
      "Imports classes or entire packages for use in the current file.",
      "",
      "import java.util.List;",
      "import java.util.ArrayList;",
      "import java.util.*;  // import all classes from package",
    },
    code_start = 5,
    code_end = 7,
  },

  -- Primitive Types
  ['int'] = {
    lines = {
      "int - Primitive Type",
      "",
      "32-bit signed integer.",
      "",
      "Range: -2,147,483,648 to 2,147,483,647",
      "Default value: 0",
      "",
      "int count = 42;",
    },
    code_start = 8,
    code_end = 8,
  },

  ['long'] = {
    lines = {
      "long - Primitive Type",
      "",
      "64-bit signed integer.",
      "",
      "Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807",
      "Default value: 0L",
      "Literal suffix: L or l",
      "",
      "long bigNumber = 9876543210L;",
    },
    code_start = 9,
    code_end = 9,
  },

  ['short'] = {
    lines = {
      "short - Primitive Type",
      "",
      "16-bit signed integer.",
      "",
      "Range: -32,768 to 32,767",
      "Default value: 0",
      "",
      "short smallNumber = 1000;",
    },
    code_start = 8,
    code_end = 8,
  },

  ['byte'] = {
    lines = {
      "byte - Primitive Type",
      "",
      "8-bit signed integer.",
      "",
      "Range: -128 to 127",
      "Default value: 0",
      "",
      "byte b = 100;",
    },
    code_start = 8,
    code_end = 8,
  },

  ['float'] = {
    lines = {
      "float - Primitive Type",
      "",
      "32-bit IEEE 754 floating point.",
      "",
      "Precision: ~6-7 decimal digits",
      "Default value: 0.0f",
      "Literal suffix: F or f",
      "",
      "float temperature = 98.6f;",
    },
    code_start = 9,
    code_end = 9,
  },

  ['double'] = {
    lines = {
      "double - Primitive Type",
      "",
      "64-bit IEEE 754 floating point.",
      "",
      "Precision: ~15 decimal digits",
      "Default value: 0.0d",
      "Literal suffix: D or d (optional)",
      "",
      "double pi = 3.14159265359;",
    },
    code_start = 9,
    code_end = 9,
  },

  ['char'] = {
    lines = {
      "char - Primitive Type",
      "",
      "16-bit Unicode character.",
      "",
      "Range: '\\u0000' to '\\uffff' (0 to 65,535)",
      "Default value: '\\u0000' (null character)",
      "",
      "char letter = 'A';",
      "char unicode = '\\u0041';  // also 'A'",
    },
    code_start = 8,
    code_end = 9,
  },

  ['boolean'] = {
    lines = {
      "boolean - Primitive Type",
      "",
      "Represents true or false values.",
      "",
      "Values: true, false",
      "Default value: false",
      "",
      "boolean isValid = true;",
    },
    code_start = 8,
    code_end = 8,
  },

  -- Special Keywords
  ['instanceof'] = {
    lines = {
      "instanceof - Type Comparison Operator",
      "",
      "Tests whether an object is an instance of a specific class or interface.",
      "Returns boolean (true or false).",
      "",
      "if (obj instanceof String) {",
      "    String str = (String) obj;",
      "}",
    },
    code_start = 6,
    code_end = 8,
  },

  ['assert'] = {
    lines = {
      "assert",
      "",
      "Tests assumptions during development. Throws AssertionError if condition is false.",
      "Disabled by default; enable with `-ea` JVM flag.",
      "",
      "assert value >= 0 : \"Value must be non-negative\";",
    },
    code_start = 6,
    code_end = 6,
  },
}

-- List of all keywords to check
M.keywords = {
  'enum', 'class', 'interface', 'public', 'private', 'protected',
  'static', 'final', 'abstract', 'synchronized', 'volatile', 'transient', 'native',
  'extends', 'implements', 'throw', 'throws', 'try', 'catch', 'finally',
  'if', 'else', 'switch', 'case', 'default', 'for', 'while', 'do', 'break', 'continue',
  'void', 'return', 'new', 'this', 'super', 'null', 'true', 'false',
  'package', 'import',
  'int', 'long', 'short', 'byte', 'float', 'double', 'char', 'boolean',
  'instanceof', 'assert'
}

-- Convert help text to markdown format matching JDTLS style
local function to_markdown(help)
  local out = {}

  -- Start with java code fence that includes the keyword title
  table.insert(out, "```java")
  table.insert(out, help.lines[1])
  table.insert(out, "```")
  table.insert(out, "")

  -- Process remaining lines (skip the title which is line 1)
  for i = 2, #help.lines do
    -- Insert code fence marker before code starts
    if help.code_start and i == help.code_start then
      table.insert(out, "```java")
    end

    -- Add the actual line
    table.insert(out, help.lines[i])

    -- Insert closing code fence after code ends
    if help.code_end and i == help.code_end then
      table.insert(out, "```")
    end
  end

  return out
end

-- Show help in a floating window (JDTLS-style)
function M.show_help(word)
  local help = help_text[word]
  if not help then
    return false
  end

  local md_lines = to_markdown(help)

  vim.lsp.util.open_floating_preview(
    md_lines,
    "markdown",
    {
      border = "rounded",
      focusable = false,
      close_events = {
        "CursorMoved",
        "CursorMovedI",
        "BufLeave",
        "InsertEnter",
      },
    }
  )

  return true
end

function M.try_show_keyword()
  local word = vim.fn.expand("<cword>")
  if vim.tbl_contains(M.keywords, word) then
    return M.show_help(word)
  end
  return false
end

return M
